#tuple->()
#datatype that is immutable(no changes can be made)
#faster that list
a=(5,55,78,4,5,8,4,54)
print("Length=",len(a))
print("Index of 54=",a.index(54))
b=("hello","hi")
print(a+b)
c=(a,b)
print(c)
